<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Iron.Cli</RootNamespace>
    <AssemblyName>iron</AssemblyName>
    <Tailcalls>true</Tailcalls>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Iron.Host/Iron.Host.fsproj" />
  </ItemGroup>
</Project>
