<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Jern.Cli</RootNamespace>
    <AssemblyName>jern</AssemblyName>
    <Tailcalls>true</Tailcalls>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Jern.Host/Jern.Host.fsproj" />
  </ItemGroup>
</Project>
